server:
  port: 8888

spring:
  profiles:
#    active: git # or native
    include:
      - git
#      - native
  security:
    user:
      name: user
      password: password

logging:
  level:
    org.springframework.cloud.config: DEBUG

---
spring:
#  profiles: git
  config:
    activate:
      on-profile: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/parvinaghazadeh/config-store.git
          cloneOnStart: true

---
spring:
  config:
    activate:
      on-profile: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/native-config